import {
  burgerBisro,
  cheesyCrust,
  padThaiPalace,
  pizzaParadise,
  sizzlingSteakhouse,
  spicySizzle,
  sushiSensation,
  sushiSpot,
  sushiSupreme,
  tacoFiesta,
  tacoTime,
  thaiShrimp,
} from "./images";

export const resList = [
  {
    type: "restaurant",
    data: {
      id: "vr34z6",
      image: spicySizzle,
      name: "Spicy Sizzle",
      cuisines: ["Thai"],
      avgRating: 4.5,
      costForTwo: 9,
      deliveryTime: "30-45 mins",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "dr78y2",
      image: cheesyCrust,
      name: "Cheesy Crust",
      cuisines: ["Italian"],
      avgRating: 4.2,
      costForTwo: 11,
      deliveryTime: "25-35 mins",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "qs23t9",
      image: sushiSensation,
      name: "Sushi Sensation",
      cuisines: ["Japanese"],
      avgRating: 4.7,
      costForTwo: 10,
      deliveryTime: "20-30 mins",
    },
  },

  {
    type: "restaurant",
    data: {
      id: "ar45u1",
      image: tacoFiesta,
      name: "Taco Fiesta",
      cuisines: ["Mexican"],
      avgRating: 4.4,
      costForTwo: 8,
      deliveryTime: "15-25 mins",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "qw67h3",
      image: sizzlingSteakhouse,
      name: "Sizzling Steakhouse",
      cuisines: ["American"],
      avgRating: 4.8,
      costForTwo: 12,
      deliveryTime: "30-40 mins",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "ty89o5",
      image: padThaiPalace,
      name: "Pad Thai Palace",
      cuisines: ["Thai"],
      avgRating: 4.6,
      costForTwo: 11,
      deliveryTime: "25-35 mins",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "pl98m2",
      image: sushiSupreme,
      name: "Sushi Supreme",
      cuisines: ["Japanese"],
      avgRating: 4.9,
      costForTwo: 10,
      deliveryTime: "20-30 mins",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "fg32l1",
      image: burgerBisro,
      name: "Burger Bistro",
      cuisines: ["American"],
      avgRating: 4.3,
      costForTwo: 9,
      deliveryTime: "15-25 mins",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "nm12j7",
      image: pizzaParadise,
      name: "Pizza Paradise",
      cuisines: ["Italian"],
      avgRating: 4.7,
      costForTwo: 11,
      deliveryTime: "30-40 mins",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "hy76k9",
      image: tacoTime,
      name: "Taco Time",
      cuisines: ["Mexican"],
      avgRating: 4.5,
      costForTwo: 8,
      deliveryTime: "20-30 mins",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "iu34p5",
      image: sushiSpot,
      name: "Sushi Spot",
      cuisines: ["Japanese"],
      avgRating: 4.2,
      costForTwo: 10,
      deliveryTime: "25-35 mins",
    },
  },
  {
    type: "restaurant",
    data: {
      id: "as21r8",
      image: thaiShrimp,
      name: "Thai Shrimp",
      cuisines: ["Thai"],
      avgRating: 4.8,
      costForTwo: 9,
      deliveryTime: "15-25 mins",
    },
  },
];
